APP_VERSION = "2.0.0-beta.5"
APP_DISPLAY_VERSION = "v2.0.0-beta.5"
APP_RELEASE_DATE = "2026-08-17"
PRODUCT_NAME = "Local Prompt Studio"
INTERNAL_APPLICATION_ID = "local_prompt_studio"
REPOSITORY_URL = "https://github.com/tarou61300/Local-Prompt-Studio"
