APP_VERSION = "3.1.0"
APP_DISPLAY_VERSION = "v3.1.0"
APP_RELEASE_DATE = "2026-08-28"
PRODUCT_NAME = "Local Prompt Studio"
INTERNAL_APPLICATION_ID = "local_prompt_studio"
REPOSITORY_URL = "https://github.com/tarou61300/Local-Prompt-Studio"
