APP_VERSION = "2.1.0"
APP_DISPLAY_VERSION = "v2.1.0"
APP_RELEASE_DATE = "2026-08-23"
PRODUCT_NAME = "Local Prompt Studio"
INTERNAL_APPLICATION_ID = "local_prompt_studio"
REPOSITORY_URL = "https://github.com/tarou61300/Local-Prompt-Studio"
